### ISSUE TITLE
Is the wind speed range 5m/s to 15m/s suitable for NREL 5MW in real world?

### ISSUE THREAD

**Issue by DeeDive** [NREL/floris#120]
Hi, I wonder that is the wind speed range 5m/s to 15m/s that FLORIS usually adopted suitable for NREL 5MW in real world? 

Recently, I did some LES simulations in SOWFA with turbine NREL 5MW. It seems the simulation throws an exception when the inflow wind speed is higher than 11m/s.

Also, I read the NREL 5MW paper, and it seems that the rated wind speed and rated rotor speed are 12m/s and 12.1 rpm.

![image](https://user-images.githubusercontent.com/42198534/81136785-1eea7a80-8f8f-11ea-89cf-f634a38e3305.png)
![image](https://user-images.githubusercontent.com/42198534/81136794-2578f200-8f8f-11ea-83da-764f2fc7bab1.png)

**Reference** 
Jonkman et al. - 2009 - Definition of a 5-MW Reference Wind Turbine for Of...

Millions of thanks in advance.

**Comment by paulf81** [comment]
hi, FLORIS relies on the input cp/ct tables per wind speed.  Its good to include a wider range of wind speeds in the input tables so that results can be interpolated rather than extrapolated (so including a point at 0 m/s and at/above 25 m/s).  Often we simulate wind roses covering this range.
