### ISSUE TITLE
Use linear interpolation instead of nearest neighbors for swept area velocities

### ISSUE THREAD

**Issue by ebranlard** [NREL/floris#136]
**Is your feature request related to a problem? Please describe.**

Nearest neighbor interpolation is used in calculate_swept_area_velocities, which can lead to some unexpected inaccuracies. 

**Describe the solution you'd like**

A linear interpolation, though slower, would reduce the error. 

Returning a warning if the nearest grid point is more than a portion of the rotor size away could also help the user if a grid too coarse is used.

**Comment by paulf81** [comment]
FLORIS v3 will not require any interpolation between points so closing issue.  It's been a wild year
