### ISSUE TITLE
About the rotate speed setting in Floris

### ISSUE THREAD

**Issue by naxingyu1** [NREL/floris#137]
Cloud you please tell me how does Floris set the rotate speed? 

I  use these equations to find the rotate speed n, and find that the rotate speed changes when wind speed changes, is that right? but I still don't know the certain equations, codes, or laws in Floris.

![image](https://user-images.githubusercontent.com/66775301/84411991-28779a00-ac41-11ea-8940-a3080708af96.png)
![image](https://user-images.githubusercontent.com/66775301/84412034-37f6e300-ac41-11ea-957a-d51866b7daec.png)
![image](https://user-images.githubusercontent.com/66775301/84412044-3cbb9700-ac41-11ea-925d-291311a29a05.png)

**Comment by paulf81** [comment]
Hi,

  FLORIS doesn’t typically model rotate speed.  Turbine information is computed generally though Cp/Ct lookup tables, where the input in wind speed, yaw angle, air density.

Paul
