### ISSUE TITLE
Request to include the file "windtoolkit_geo_center_us.p"

### ISSUE THREAD

**Issue by fabiodominguezs** [NREL/floris#147]
I am new at Floris and currently trying to use the "compute_aep.py" example to calculate the AEP of a 200 turbine wind farm fro each turbine.

I would like to use my own wind field by loading a wind rose file. In the case of this example, between the lines 101 and 103 we have:

	df = wind_rose.load(os.path.join(
		file_dir, '../optimization/scipy/windtoolkit_geo_center_us.p'
	))

My idea is to modify the file "windtoolkit_geo_center_us.p", but when I search for it in ../floris/floris/tools/optimization/scipy/
I can't find this file. Could you please upload it?

**Comment by ejsimley** [comment]
Hi @fabiodominguezs, this file is located in the folder 'floris/examples/optimization/scipy/'. Are you able to find it there? Let us know if you have any more questions about how the wind rose data frames are structured!

**Comment by fabiodominguezs** [comment]
Hi ejsimley,

Thank you for your mail. The file is there but I cannot read it in Anaconda
to modify parameters, but it works for Floris as df.

Kind regards,

Fabio

**Comment by ejsimley** [comment]
Hi Fabio, 

Since the wind rose is saved as a binary pickle file it should be loaded as a DataFrame before you can see the contents. Once it is loaded (as you showed above), then you can see how it is structured and modify the wind direction, wind speed, and frequency columns if you'd like. But it sounds like you were able to use `WindRose.make_wind_rose_from_user_data` instead?

Eric

**Comment by fabiodominguezs** [comment]
Hi Eric,

Exactly, I used the same logic from the aep calculation example:

df = WindRose.make_wind_rose_from_user_data(ws_raw,wd_raw)

In which ws_raw and wd_raw are 1-dimension lists of wind speed and wind
direction data from my wind field.

And further use for the othe WindRose submodules.

Thank you very much for your support!

Kind regards,

Fabio
