### ISSUE TITLE
Example of *args in "make_wind_rose_from_user_data" submodule

### ISSUE THREAD

**Issue by fabiodominguezs** [NREL/floris#148]
I am using the "make_wind_rose_from_user_data" submodule of "WindRose" Tools module and I don't understand which input data I should use for "*args" input data. Could you give me an example of *args please?

*args: Variable length argument list consisting of a sequence of
                the following alternating arguments:
                
                -   string - Name of additional wind parameters to include in
                    wind rose.
                -   array-like - Values of the additional wind parameters used
                    to calculate the frequencies of occurance
                -   np.array - Bin center values for binning the additional
                    wind parameters.

make_wind_rose_from_user_data(self,wd_raw,ws_raw,*args,wd=np.arange(0, 360, 5.),ws=np.arange(0, 26, 1.))

**Comment by ejsimley** [comment]
If you only want to include wind direction and wind speed in your wind rose, then you don't have to specify anything for the *args input. This is provided in case you want to add extra variables to the wind rose, for example, turbulence intensity or wind shear.

As an example, let's say we have some wind speed and wind direction measurements and want to make a wind rose that will contain the frequency of each wind speed and direction combination:

wd_raw = [0, 0, 15, 270, 270, 355, 280, 180, 90, 0]
ws_raw = [5, 8, 7, 3, 5, 10, 4, 7, 6, 10]

Then we could create a wind rose object using:
make_wind_rose_from_user_data(wd_raw,ws_raw)

Now let's say we also have turbulence intensity measurements and want to include those as a third variable in the wind rose called 'ti'.

ti_raw = [0.1, 0.15, 0.08, 0.2, 0.25, 0.05, 0.1, 0.15, 0.2, 0.1]

*args allows us to specify the name of the new variable, followed by the raw data, then the bin center values for binning the data in the wind rose. So if we want TI to be binned in 5% increments from 0 to 30%, we could call:
make_wind_rose_from_user_data(wd_raw,ws_raw,'ti',ti_raw,np.arange(0,0.3,0.05)) 

*args allows as many extra variables as a user wants, as long as it follows the same pattern of name, raw data, bin centers.

**Comment by fabiodominguezs** [comment]
Dear ejsimley,

Thank you very much for your help! After a while I have been able to use my
wind field data in make_wind_rose_from_user_data, I had some trouble with
the data type, since it is a csv file and some convertions were needed to
finally get the list of raw wind speed and raw wind directions.

Now everything seems ok!

Kind regards,

Fabio

**Comment by ejsimley** [comment]
Glad it's working for you now!

Eric
