### ISSUE TITLE
compute_aep example not working for V2.2.0

### ISSUE THREAD

**Issue by moptis** [NREL/floris#161]
See screenshot below. Example was working in V2.1.1.

![image](https://user-images.githubusercontent.com/32751681/96037003-7df7c980-0e22-11eb-83de-3623b634f3d4.png)

**Comment by bayc** [comment]
@moptis The example needs to be updated, which we will do soon in an update. To get it to work for now, remove `turbine.average_velocity` as an input to the `turbine.u_prime(turbine.average_velcocity)` call on line 70.
