### ISSUE TITLE
add __version__attributes

### ISSUE THREAD

**Issue by yinxiEquinor** [NREL/floris#163]
**Is your feature request related to a problem? Please describe.**
with new releases recently, need to check current version installed

**Describe the solution you'd like**
add the __version__ attribute that can output current version installed through "floris.__version__"

**Describe alternatives you've considered**
it seems to be a simple feature, don't think need alternatives

**Additional context**

**Comment by bayc** [comment]
Thank you for suggesting this feature! It has been added in commit 5fb6003acb563548ab2b7bfbeba83fc13f4965dd.
