### ISSUE TITLE
json_example - calculate_wake()

### ISSUE THREAD

**Issue by TanguyLevent** [NREL/floris#165]
I've an issue when implementing the examples with your code by calling calculate_wake() function. 

_TypeError: u_prime() takes 1 positional argument but 2 were given_

**Comment by bayc** [comment]
Which example are you trying to run? Or could you provide an example of how you are using the `calculate_wake` function?

**Comment by TanguyLevent** [comment]
Thanks for the quick answer. Yes of course, I can provide:

`fi = wfct.floris_interface.FlorisInterface("floris/examples/example_input.json")
 fi.calculate_wake()
`

**Comment by bayc** [comment]
Could you provide the stacktrace from the error (just copy and paste everything from when you executed the file to the end of the error message)? I just ran the above example from the latest version of FLORIS on the `main` branch, and I do not see the error. Also, do you know what version of FLORIS you are using? You can find out by looking at the file `setup.py` and finding the `VERSION` attribute towards the top of the file.

**Comment by TanguyLevent** [comment]
I have resolve the issue after reinstall python. I don't really understand why I had the error previously because I really change anything from my code. 
Thank you a lot for your quick answer!
