### ISSUE TITLE
eps_gain property requested in Jimenez Parameters, even though it isn't defined there

### ISSUE THREAD

**Issue by zerweck** [NREL/floris#172]
`eps_gain` is a property in the parent class `VelocityDeflection`;
https://github.com/NREL/floris/blob/033c405be19002144f66636074e1b4517d45ca02/floris/simulation/wake_deflection/base_velocity_deflection.py#L235

However, the `Jimenez` class does not define the property and therefore methods such as `get_model_parameters`
fail:
```python
`fi.get_model_parameters()`
AttributeError: 'Jimenez' object has no attribute '_eps_gain'
```

Reproducible example:
```python
fi_jensen = wfct.floris_interface.FlorisInterface("../examples/other_jsons/jensen.json")
fi_jensen.get_model_parameters()
```

Suggested solution:
Remove this definition from the parent class. I would assume that curl deflection will also throw this error, since it does not define (or need) this property.

**Comment by bayc** [comment]
@zerweck This has been addressed in a recent merge to both the `main` and `develop` branches. Thanks for pointing this out!
