### ISSUE TITLE
Loading .vtk files generated by flow_data.save_as_vtk

### ISSUE THREAD

**Issue by xhlulu** [NREL/floris#187]
I'm currently going through `examples/flow_interaction/flow_data_to_vtk.py` and I was able to save the output as a vtk file. However I'm having trouble understanding the best way to load it using the python `vtk` library. I tried incorporating the result from this [SO thread](https://stackoverflow.com/questions/37572496/how-to-read-a-structured-points-vtk-file), resulting in this:
```python
import floris.tools as wfct
import vtk
from vtk.util import numpy_support
from dash_vtk.utils import to_volume_state

fi = wfct.floris_interface.FlorisInterface("./data/example_input.json")

fi.calculate_wake()

# Get the flow data and save to vtk
flow_data = fi.get_flow_data()
flow_data.save_as_vtk("./data/flow.vtk")

path = 'path_to_file.vtk'

reader = vtk.vtkDataReader()
reader.SetFileName(path)
reader.Update()

# try to get output
reader.GetOutput()
```

However I get the following error:
```
2021-02-11 16:12:03.656 (   0.783s) [        18C36740]       vtkAlgorithm.cxx:867    ERR| vtkDataReader (0x55ea96203050): FillOutputPortInformation is not implemented.
2021-02-11 16:12:03.656 (   0.783s) [        18C36740]vtkDemandDrivenPipeline:633    ERR| vtkReaderExecutive (0x55ea9616ac30): Algorithm vtkDataReader(0x55ea96203050) did not create output for port 0 when asked by REQUEST_DATA_OBJECT and does not specify any DATA_TYPE_NAME.

...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'vtkmodules.vtkIOLegacy.vtkDataReader' object has no attribute 'GetOutput'
```

I've also looked into how to load it using vtk.js, but it seems like the format is legacy and support is limited (see [this thread](https://discourse.vtk.org/t/vtk-js-api-to-load-vtk-file-for-volume-rendering/2069)).

I'd be happy to look at any example that would show how to load it in Python or JS.

**Comment by Bartdoekemeijer** [comment]
This seems more like a question rather than a bug report or a feature request. Please post these kinds of questions on [StackOverflow](https://stackoverflow.com/questions/tagged/floris) in the future.

Concerning the issue at hand: something we have been doing internally is using the Python `meshio` package to read VTK files. I found that these legacy files are problematic with the `vtk` library in Python.
```
import meshio
import numpy as np
import pandas as pd


# Read the VTK file using meshio
print('Reading VTK file using meshio.')
mesh = meshio.read(filename=filename,
                    file_format='vtk')

# Get mesh points
points = mesh.points
mesh_type = list(mesh.cells_dict.keys())[0]
cells = list(mesh.cells_dict.values())[0]

# Convert points and cells to cell centers
cell_corners = points[cells]
cell_centers = np.mean(cell_corners, axis=1)
U_data = mesh.cell_data['UMean'][0]

# Save as feather
df = pd.DataFrame({
    'x': cell_centers[:, 0],
    'y': cell_centers[:, 1],
    'z': cell_centers[:, 2],
    'u': U_data[:, 0],
    'v': U_data[:, 1],
    'w': U_data[:, 2] 
})
```

**Comment by paulf81** [comment]
Thanks Bart!
