### ISSUE TITLE
Feature request: error or warn when setting default parameters

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#189]
**Bug description**
Not exactly a bug, but an issue I've hit is that if you enter parameters into the JSON and make a mistake somewhere, rather than producing an error, default values will be used.  This can be detected by warnings but might go un-noticed, perhaps a new feature could be to check the JSON for defined parameters which aren't used or expected and forcing the user to either delete or correct the JSON?

**Comment by bayc** [comment]
This has been addressed in the new yaml format in v3 using the `attrs` package, and will alert the user if any of the required inputs are missing (either completely or mispelled), or if any additional ones were specified that shouldn't be there.
