### ISSUE TITLE
Bug report: Curl regression rotation test requires a fudge factor

### ISSUE THREAD

**Issue by bayc** [NREL/floris#196]
**Bug description**
The `test_regression_rotation` in `curl_regression_test.py` requires a fudge factor the the second waked turbine to pass.

**To Reproduce**
1. Remove the `rel` inputs to the `approx` functions in the `test_regression_rotation` test in `curl_regression_test.py`.
2. Run test with `pytest curl_regression_test.py`
3. See this error:
```
        turbine = floris.farm.turbine_map.turbines[1]
        assert approx(turbine.Cp) == first_waked_baseline[0]
        assert approx(turbine.Ct) == first_waked_baseline[1]
        assert approx(turbine.power) == first_waked_baseline[2]
        assert approx(turbine.aI) == first_waked_baseline[3]
        assert approx(turbine.average_velocity) == first_waked_baseline[4]
    
        turbine = floris.farm.turbine_map.turbines[2]
>       assert approx(turbine.Cp, ) == second_waked_baseline[0]
E       assert 0.44634920611531154 ± 4.5e-07 == 0.4463486980205582
E        +  where 0.44634920611531154 ± 4.5e-07 = approx(0.44634920611531154)
E        +    where 0.44634920611531154 = <floris.simulation.turbine.Turbine object at 0x7fdd7c77ded0>.Cp

curl_regression_test.py:151: AssertionError
=================================================================================== short test summary info ====================================================================================
FAILED curl_regression_test.py::test_regression_rotation - assert 0.44634920611531154 ± 4.5e-07 == 0.4463486980205582
================================================================================= 1 failed, 4 passed in 57.07s =================================================================================
```

**Expected behavior**
It is expected for the test to pass without needing the `rel` inputs.

**Screenshots, if applicable**
None.

**Floris Version**
v2.3.0

**System Information (please complete the following information):** 
 - OS: Ubuntu 18.04 on WSL
 - Library versions
   * matplotlib==3.2.2
   * numpy==1.19.5
   * pytest==5.4.3
   * scipy==1.6.1
   * Sphinx==3.5.2

**Additional context**
None.

**Comment by rafmudaf** [comment]
@bayc I think we can close this since its specific to v2.3. What do you think?

**Comment by bayc** [comment]
@rafmudaf  Yea, agreed!
