### ISSUE TITLE
Bug on FLORIS init with v2.3.0

### ISSUE THREAD

**Issue by StefanoWind** [NREL/floris#200]
**Bug description**
The basic installation does not install VERSION causing __init__ to crash:

**To Reproduce**
1. In command prompt (Windows 10) "pip install floris"
2. In IDLE shell import floris
3. See the error:
with open(ROOT.parent / "VERSION") as version_file:
FileNotFoundError: [Errno 2] No such file or directory

**Expected behavior**
The Floris package should be imported

**Floris Version**
2.3.0

**System Information (please complete the following information):** 
 - OS: Windows 10

**Additional context**
<Add any other context about the problem here.>

**Comment by rafmudaf** [comment]
Hi @StefanoWind - Thank you for reporting this problem. We have fixed this and re-released this version with a slightly different version number (2.3) to comply with [PEP 440](https://www.python.org/dev/peps/pep-0440/). The new package has been uploaded to PyPI and conda-forge.

Could you try installing again and report back?

**Comment by StefanoWind** [comment]
Hi Rafael,

thanks for the quick feedback. I have upgraded my pip version and now it correctly installs VERSION.

Thanks so much!

Best,

Stefano Letizia

Ph.D. Candidate - Research Assistant

The University of Texas at Dallas

________________________________

**Comment by rafmudaf** [comment]
Excellent, thanks!
