### ISSUE TITLE
Feature request: Turbine identifiers

### ISSUE THREAD

**Issue by Bartdoekemeijer** [NREL/floris#225]
**Is your feature request related to a problem? Please describe.**
Often, a FLORIS model is an abstraction of a real wind farm. Within those wind farms, turbines have typical identifiers such as A1-A9, B1-B5 and C14-C22, rather than integers from `0` to `num_turbs-1`. I often find myself generating a `mapping.csv` file that shows what turbine number in FLORIS correspond to what turbine in the actual farm. I believe that being able to keep track of the turbine names and generate visualizations with the right turbine names would be a valuable addition to floris.

**Describe the solution you'd like**
An (optional) additional input in the floris input .jsons to specify the turbine names. These turbine identifiers are never used in the actual core code, but rather only used in visualizations and as a useful way for the user to keep track of the turbines.

**Describe alternatives you've considered**
I now have a practice where I create a wrapper class for floris wherein I save a variable called "turbine_names" that can be returned to the user upon request.

**Additional context**
This is a minor suggestion, and by no means urgent. I'd like to hear whether others think this is useful.

**Comment by bayc** [comment]
Thanks for this suggestion Bart! I agree, we have a need for turbine identifiers for many reasons (I find myself needing them in layout/yaw optimization). This is currently on my list of things to get included in FLORIS 3.0, so if nothing else, it should be in the next version. But know that it is being worked on and should be available in the near future.
