### ISSUE TITLE
Bug report: Flowfield with multiple wind speed measures

### ISSUE THREAD

**Issue by Josue9740** [NREL/floris#234]
**Bug description**
I am not sure if this is a bug report or a need for enhancement declaration. When the flow filed is estimated drawing on a different wind speed measure for every turbine, the resulting calculation is somewhat strange. 

**To Reproduce**
I am running a code like the next one. If we use 10 m/s for every turbine instead of 10, 11, 12 and 13 m/s, the resulting flow field is correct. However, using different speeds provides a strange flowfield calculation, like the one in the attached picture. 

turb1_ws, turb2_ws, turb3_ws, turb4_ws = 10.0, 11.0, 12.0, 13.0
turb1_wd, turb2_wd, turb3_wd, turb4_wd = 20.0, 20.0, 20.0, 20.0
wind_speed = [turb1_ws,turb2_ws,turb3_ws,turb4_ws]
wind_direction = [turb1_wd,turb2_wd,turb3_wd,turb4_wd]

fi.reinitialize_flow_field(wind_speed = wind_speed,
                           wind_direction = wind_direction,
                           wind_layout = (layout_x,layout_y),
                           layout_array=(layout_x,layout_y))
fi.calculate_wake()
# Flowfield limits
xmin, xmax = -2000.0,2200.0
ymin, ymax = -2000.0,2200.0
ti = 0.102
# Initialize the horizontal cut
hor_plane = fi.get_hor_plane(height=fi.floris.farm.turbines[0].hub_height,
                             x_bounds=(xmin,xmax),
                             y_bounds=(ymin,ymax))
# Plot
fig, ax = plt.subplots()
im = wfct.visualization.visualize_cut_plane(hor_plane, ax=ax)
wfct.visualization.plot_turbines_with_fi(ax, fi)
cbar = fig.colorbar(im,ax=ax,fraction=0.10,pad=0.04)
cbar.set_label('m/s', labelpad=+10)
ax.set_title('Flujo para U = {} m/s, Dirección: {}$^\\circ$, IT: {}%'.format(
                                            wind_speed,
                                            wind_direction,round(ti*100,2)))
plt.show()

**Expected behavior**
The graphical result should show a proper flowfield. However, it results in distorted flow lines and unreasonable colours (see attached picture). 

![Figure_10](https://user-images.githubusercontent.com/86227863/124591284-08baa180-de54-11eb-87da-ce88fc61beae.png)

**Floris Version**
Floris 2.3

**Comment by Josue9740** [comment]
We can compare with the correct flow field. As it can be seen, flow lines seem much more reasonable, and the color map in the graph is more homogenous:

![Figure_11](https://user-images.githubusercontent.com/86227863/124592232-23d9e100-de55-11eb-8e89-9da202216530.png)

**Comment by bayc** [comment]
It looks like you are using the heterogenous input functionality of FLORIS by defining wind speeds and directions at each turbine. With this type of input, an interpolation is done between the wind layout points provided to generate the background flow field. The contours you see on your first plot are a result of that interpolation and are expected based on your input. We often use this feature to describe a heterogenous inflow across one side of the flow field. If you are looking for a smoother transition across the background flow, you can try defining additional wind layout points.

**Comment by bayc** [comment]
@Josue9740 Was your issue resolved? Or did my above comment not address your concern?

**Comment by Josue9740** [comment]
Hi! Yes, your comments resolved the issue. I will close the case.
Thank you so much.
