### ISSUE TITLE
Suggestions for user-friendliness: Add more methods and properties to Floris or FlorisInterface

### ISSUE THREAD

**Issue by petebachant** [NREL/floris#25]
It would be great if the `Floris` and/or `FlorisInterface` classes (what is the difference?) had methods that wrapped up other functionality like running wake steering optimization and plotting.

For example:

```python
import floris

sim = floris.Floris(input_file="my_config.json")
ax1 = sim.plot_horizontal_slice(figsize=(10, 5))
ax1.set_title("Baseline")
sim_ws = sim.copy()  # Could return a deepcopy of itself
sim_ws.run_wake_steering()
power_ratio = sim_ws.total_power / sim.total_power
print("Optimum yaw:", sim_ws.yaw_angles)
ax2 = sim_ws.plot_horizontal_slice(figsize=(10, 5))
ax2.set_title("Optimized")
```

**Comment by paulf81** [comment]
Thanks @petebachant for these comments.  To your first point, the floris_interface is like you say a wrapper that provides some convenience methods down to the floris wake simulation codes.  Right now there is also a sowfa_interface, and we hope to add interfaces to other codes going forward.  The idea of splitting visualization methods out of the classes, is to follow an overall pattern of one interface method that can accept an interface to floris, or sowfa, or other codes with a standard interface.  All that said, we can additional links within the class and these suggestions are useful.  We have a batch of changes queuing up for the next major revision and these thoughts will factor in.

**Comment by paulf81** [comment]
Closing this issue doing a sweep up, but we still agree with the sentiment, and V3.1 and V3.2 will see more features included into the interface.
