### ISSUE TITLE
Bug report: Error when representing XZ and YZ planes with a heterogeneous flowmap

### ISSUE THREAD

**Issue by Josue9740** [NREL/floris#253]
**Bug description**
I found an important error when creating plots of XZ and YZ planes with a heterogeneous flowmap: the simulation is roughly interrupted, no graphs are created and the Python kernel automatically restarts without raising any exception. However, the same code (changing "get_cross_plane" by "get_hor_plane") perfectly works for XY planes. 

**To Reproduce**
The code would be something like that:

    # fi object with wlayout = wind measure points
    fi.reinitialize_flow_field(wind_speed = wind_speed, 
                                wind_direction = wind_direction, 
                                wind_layout = (wlayout_x,wlayout_y), 
                                layout_array=(layout_x,layout_y))
    fi.calculate_wake()

    # Flowfield limits
    xmin, xmax = xleft-3000,xright+3000 #xleft-1000,xright+D
    ymin, ymax = ydown-4000,yup+2000 #ydown-2000,yup+D

    # Initialize the cut where gpht= turbine number, hmax=imput for vertical scale
    cross_plane = fi.get_cross_plane(x_loc=layout_x[gpht],y_bounds=(
        layout_y[gpht]-1666,layout_y[gpht]+10),z_bounds=(0,hmax*2))

    # Plot
    fig, ax = plt.subplots(figsize=(2000/dpi,2000/dpi),dpi=dpi)
    im = wfct.visualization.visualize_cut_plane(cross_plane, ax=ax, minSpeed=0.0, maxSpeed=15.0)
    cbar = fig.colorbar(im,ax=ax,fraction=0.10,pad=0.01)
    cbar.set_label('Velocidad del viento\n[m/s]', labelpad=+10,fontsize=15)
    cbar.ax.tick_params(labelsize=12)

**Expected behavior**
Get XZ and YZ planes for heterogeneous flowmap

**Comment by bayc** [comment]
This appears to function as intended in v3.0, shown in: https://github.com/NREL/floris/blob/main/examples/13_heterogeneous_inflow.py.
