### ISSUE TITLE
Feature request: dynamic wake predictions

### ISSUE THREAD

**Issue by pjireland** [NREL/floris#267]
**Is your feature request related to a problem? Please describe.**
While FLORIS predicts steady-state waking behavior, it would be nice to have the ability to predict the dynamic evolution of wakes.

Some work has been undertaken by others to extend FLORIS to provide time-dependent wake predictions. Two examples are [this implementation in Python](https://github.com/PStanfel/floris) (see https://ieeexplore.ieee.org/abstract/document/9483277 for more details) and [this implementation in Matlab](https://github.com/JuliusAurelius/FLORIDyn).

**Describe the solution you'd like**
The ability to obtain time-dependent wake predictions for time-varying and spatially heterogeneous wind speeds and wind directions.

**Comment by rafmudaf** [comment]
Hi @pjireland - Currently, NREL does not plan to develop a dynamic model for FLORIS. However, we are interested in partnering with groups who are working in this area to use FLORIS and potentially integrate this feature into this repository.
