### ISSUE TITLE
Feature request: Return No-Wake Farm Power from SR Optimization

### ISSUE THREAD

**Issue by scottryn** [NREL/floris#271]
**Is your feature request related to a problem? Please describe.**
Computing farm power without wake losses is important for quantifying gains from wake steering. This functionality was present in prior optimization versions with calc_baseline_power() although it appears to have been removed with the recent serial refinement update. Baseline power is also a required input to generate a power rose and possibly others.

**Describe the solution you'd like**
An internal function to compute no-wake farm power for each inflow condition and include it in the optimal yaw data frame.

**Describe alternatives you've considered**
It is possible to compute the no-wake power by iterating over inflow conditions in a separate script after optimization.

**Additional context**
This is a minor suggestion and the current alternative works in the meantime.

**Comment by Bartdoekemeijer** [comment]
Hey Ryan. Could you please check out #275 and see if this meets your needs? Thanks!

**Comment by scottryn** [comment]
Hi Bart. Thanks for taking a look at this! #275 is exactly the functionality I need.
