### ISSUE TITLE
Include uncertainty options in the input file and fi.reinitialize()

### ISSUE THREAD

**Issue by rafmudaf** [NREL/floris#287]

**Comment by Bartdoekemeijer** [comment]
This has been pulled in with #308. We decided not to include uncertainty in the input file, but rather design a wrapper around the `FlorisInterface` object that adds uncertainty. That feature is called `UncertaintyInterface`. Note that this is only one method for including uncertainty with FLORIS, and therefore has not been made part of the core code.
