### ISSUE TITLE
FlorisInterface.reinitialize_flow_field wake

### ISSUE THREAD

**Issue by knutss** [NREL/floris#31]
**Bug description**
In FlorisInterface.reinitialize_flow_field there seem to be a possibility to change the wake model by including a wake string argument which is passed on to flow_field.reinitialize_flow_field, but reinitialize_flow_field expects a floris.simulation.wake class and thus gives an error.

**To Reproduce**
Include e.g. wake='gauss' as an argument to FlorisInterface.reinitialize_flow_field and get error message "AttributeError: 'str' object has no attribute 'velocity_model'".

**Comment by bayc** [comment]
Hello, and thank you for your contribution to FLORIS, @knutss !

After reviewing the bug, we identified an error in the documentation and that the code is behaving properly. The `wake` argument to `FlorisInterface.reinitialize_flow_field()` should be a `floris.simulation.wake` class object.

The documentation has been updated on the [develop](/NREL/floris/tree/develop) branch. The new documentation can be viewed [here](https://floris.readthedocs.io/en/develop/source/classes/floris.tools.floris_utilities.html#floris.tools.floris_utilities.FlorisInterface.reinitialize_flow_field).

There is a method in place to change the wake model being used in the FLORIS simulation, `set_wake_model`, with documentation [here](https://floris.readthedocs.io/en/develop/source/classes/floris.simulation.farm.html#floris.simulation.farm.Farm.set_wake_model). The method is used in an example [here](https://github.com/NREL/floris/blob/develop/examples/example_0007_vis_curl.py#L22).

Thank you again for pointing out this issue.
