### ISSUE TITLE
`fi.floris.turbine_map` equivalent in v3

### ISSUE THREAD

**Issue by vijay092** [NREL/floris#321]
### Discussed in https://github.com/NREL/floris/discussions/320

<div type='discussions-op-text'>

<sup>Originally posted by **vijay092** February 16, 2022</sup>
Looks like `fi.floris.turbine_map` has been removed from FLORIS 3.0. Is there an equivalent in the new version?
I would like to perform the following operation:
```

for coord, turbine in fi.floris.farm.turbine_map.items:
        ct.append(turbine.Ct)
        ai.append(turbine.aI)
        ave_vel.append(turbine.average_velocity)

```

**Comment by rafmudaf** [comment]
Let's talk about this in the discussion ->
