### ISSUE TITLE
Bug report: layout constraint and minimum distance definition

### ISSUE THREAD

**Issue by MYMahfouz** [NREL/floris#363]
**The second constraint: distance from boundary**
The constraint is defined with a lower bound as zero. Zero is the upper bound according to the constraint function. 
This can be fixed by changing line 104 in floris.tools.optimization.pyoptsparse.layout.py
``` python 
optProb.addConGroup("boundary_con", self.nturbs, upper=0.0)

````

**The minimum distance is fixed and not read from the turbine input**
The value of the turbine diameter is fixed to 126 m instead of reading the turbine diameter.
This can be fixed by updating the last line in floris.tools.optimization.pyoptsparse.layout.py

**Comment by bayc** [comment]
Thanks for the bug report! I will look into this today and get it addressed.

**Comment by MYMahfouz** [comment]
Happy to help. Thanks for adding the function to the new release.
