### ISSUE TITLE
Feature request: ability to disable wake deflection submodel to speed up calculations

### ISSUE THREAD

**Issue by Bartdoekemeijer** [NREL/floris#394]
**Is your feature request related to a problem? Please describe.**
#270 suggests the option to assign "None" to the wake deflection model choice, which then skips those calculations. This can further speed up computations for when we are not interested in wake deflection.

**Describe the solution you'd like**
Ability to assign `None` to the wake deflection submodel. Perhaps something similar for other submodel types, such as the local turbulence model and perhaps even the wake deficit model, assuming it is simple to do.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by paulf81** [comment]
This seems like a good idea to me too

**Comment by rafmudaf** [comment]
One idea for implementing this is to have a "no_deflection" wake deflection model that simply returns zero. Something like this:

```Python
@define
class NoDeflection(BaseModel):
    """
    Don't do anything
    """

    model_string = "none"

    def prepare_function(
        self,
        grid: Grid,
        flow_field: FlowField,
    ) -> Dict[str, Any]:
        return dict()

    # @profile
    def function(
        self,
        x_i: np.ndarray,
        y_i: np.ndarray,
        yaw_i: np.ndarray,
        turbulence_intensity_i: np.ndarray,
        ct_i: np.ndarray,
        rotor_diameter_i: np.ndarray,
        *,
        x: np.ndarray,
    ):
        return 0.0
```

I think a scalar 0.0 will work but that should be double checked. If not, you could get `grid.x` in the prepare function and use that to get the right shape for `np.zeros()`.

**Comment by Bartdoekemeijer** [comment]
@rafmudaf this is exactly what I have implemented. I was just struggling with GitHub and pushing up that branch to my fork, but essentially that is what I did for the deflection, deficit and added turbulence models.
