### ISSUE TITLE
Documentation on how to get the wind speed at each turbine

### ISSUE THREAD

**Issue by carlorop** [NREL/floris#422]
**Is your feature request related to a problem? Please describe.**
The documentation has diminished in FLORIS v 3.0. Some features can be understood easily reading the code or going through the examples, however it would be convenient to expand the documentation. For instance, explaining hot to get the wind speed at each turbine 

**Additional context**
In FLORIS 2.4. the code for getting such velocity would be:
```python
velocity_at_each_turbine = []
for i in range(len(self.fi.floris.farm.flow_field.turbine_map.turbines)):
    velocity_at_each_turbine.append(self.fi.floris.farm.turbines[i].average_velocity)
```

**Comment by paulf81** [comment]
Thanks very much for this feedback!  I've created pull request #423 which adds a new example for getting wind speeds.  Does this work?  More generally we're hoping to add much more documentation going forward.
