### ISSUE TITLE
Restore get_set_of_points funct

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#425]
Get set of points function is there but need to verify it works across wake models and add examples

### Discussed in https://github.com/NREL/floris/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **benoitFoloppe** April 14, 2022</sup>
Hello,

I am wondering if in the new version of Floris (V3), there is an equivalent function to `get_set_of_points` (in `floris_interface.py`) that was available before ? What I need is to be able to extract velocity values along a line or at a single location.

Best regards,</div>

**Comment by rafmudaf** [comment]
Closed by #650
