### ISSUE TITLE
Feature request:  write 'assign_hub_height_to_ref_height' for 'UncertaintyInterface' 

### ISSUE THREAD

**Issue by julienMs** [NREL/floris#426]
**Is your feature request related to a problem? Please describe.**
<A clear and concise description of the problem.>

**Describe the solution you'd like**
<A clear and concise description of what you want to happen.>

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features youve considered.>

**Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by Bartdoekemeijer** [comment]
Hi @julienMs! Thanks for raising this issue. I have opened pull request #428. Please check it out and let me know if it meets your needs!
