### ISSUE TITLE
Feature request: interface to retrieve the turbulence intensity at individual turbines in the flow

### ISSUE THREAD

**Issue by pjireland** [NREL/floris#442]
**Is your feature request related to a problem? Please describe.**
I would like to be able to know the turbulence intensity of waked turbines for loads analysis, which was possible in FLORIS 2.4.

**Describe the solution you'd like**
Provide an interface to retrieve the turbulence intensity at each turbine similar to the methods `get_turbine_Cts()`, `get_turbine_powers()`, `get_turbine_ais()`, and `get_turbine_average_velocities()` in `FlorisInterface`.
In FLORIS 2.4, we could access the turbulence intensity at individual turbines through the `current_turbulence_intensity` property of the `turbine_map`. Is there a way to access something similar in FLORIS 3.1?

**Describe alternatives you've considered**

**Additional context**

**Comment by bayc** [comment]
@pjireland  We do keep track of the TIs calculated at the turbines in the solver. I have added a method to retrieve these values to `floris_interface` that can be called after a `calculate_wake` call in PR #452 . If you have a chance, please try out and give feedback on if this the functionality you are looking for.

**Comment by bayc** [comment]
@pjireland Sure thing! We will work to get this included into develop and then main.

**Comment by rafmudaf** [comment]
Resolved by #452.
