### ISSUE TITLE
Bug report: `plot_turbines_with_fi` throws an error because it attempts to use `get_yaw_angles`

### ISSUE THREAD

**Issue by pjireland** [NREL/floris#443]
**Bug description**
`plot_turbines_with_fi` throws an error because it attempts to call `fi.get_yaw_angles()`, which no longer exists in FLORIS 3.1.

**To Reproduce**
<Update the following list with your specific information.>
1. Run `plot_turbines_with_fi` for any simulation in FLORIS 3.1.
2. Receive an error like the one below:
```
-> 1167 plot_turbines_with_fi(fi=sim, ax=ax)

File ~\Anaconda3\envs\wedev-new-floris\lib\site-packages\floris\tools\visualization.py:70, in plot_turbines_with_fi(ax, fi, color)
     54 def plot_turbines_with_fi(ax, fi, color=None):
     55     """
     56     Wrapper function to plot turbines which extracts the data
     57     from a FLORIS interface object
   (...)
     64         color (str, optional): Color to plot turbines
     65     """
     66     plot_turbines(
     67         ax,
     68         fi.layout_x,
     69         fi.layout_y,
---> 70         fi.get_yaw_angles()[0, 0],
     71         fi.floris.farm.rotor_diameter[0, 0],
     72         color=color,
     73         wind_direction=fi.floris.flow_field.wind_directions[0],
     74     )

AttributeError: 'FlorisInterface' object has no attribute 'get_yaw_angles'
```

**Expected behavior**
The plot should be generated successfully.

**Floris Version**
Version 3.1 from Pip.

**System Information (please complete the following information):** 
 - OS: Windows 10.
 - Library versions
   * matplotlib: 3.5.2
   * numpy: 1.22.3
   * pytest: 7.1.2
   * scipy: 1.8.1

**Additional context**
<Add any other context about the problem here.>

**Comment by rafmudaf** [comment]
Fixed by #445
