### ISSUE TITLE
Pip-install does not include "turbopark_lookup_table.mat"

### ISSUE THREAD

**Issue by rafmudaf** [NREL/floris#447]
### Discussed in https://github.com/NREL/floris/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **mr483** June 22, 2022</sup>
When trying to use the Turbopark model, I received the error that the file "turbopark_lookup_table.mat" could not be found. Downloading it from Github and adding it in the wake_velocity folder fixed this. I tried installing FLORIS on a new environment and could reproduce the issue, so it seems the file is not included when installing via pip.  </div>

**Comment by mr483** [comment]
> @mr483 I've created a new release tagged v3.1.1 that should fix this issue. Could you test after about 30 minutes?

Confirmed on a new installation that the file is included. Thanks
