### ISSUE TITLE
Remove unnecessary variable assignment in model functions and core simulation architecture

### ISSUE THREAD

**Issue by RHammond2** [NREL/floris#471]
**Is your feature request related to a problem? Please describe.**
This is related to how FLORIS/NumPy struggles with large problem spaces, and optimizing how we we've created our calculations

**Describe the solution you'd like**
Identify intermediate calculations where there are unnecessary memory allocations, and reduce these to the essential variable creation steps in calculations for potential NumPy memory and speed efficiency gains

**Describe alternatives you've considered**
This is the easiest step in a longer series of potential solutions, such as:
- NumExpression (partially in use currently with definite speedups where it's in use)
- Numba (tried previously, but is finnicky between versions and what NumPy functionality is being used)
- Cython (likely a longer term solution to speed up our unavoidable for loops in sequential solving

**Additional context**
The main finding relating to FLORIS's speed in a roundup of [NumPy vectorization problems](https://pythonspeed.com/articles/vectorization-python-alternatives/) is likely unnecessary large memory allocations.

**Comment by paulf81** [comment]
Thank you for starting this thread Rob
