### ISSUE TITLE
Add times series option to UncertaintyInterface

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#516]
**Is your feature request related to a problem? Please describe.**
It would be useful to follow FlorisInterface and allow the ws/wd to be passed in in time series form.

**Describe the solution you'd like**
UncertaintyInterface to include time_series flag just with IO/functionality matched to FlorisInterface

**Comment by misi9170** [comment]
@paulf81 I believe the intended behavior is now incorporated in the `UncertainFlorisModel` in v4, and this issue can be closed?

**Comment by paulf81** [comment]
Oh yeah, this is done, good catch
