### ISSUE TITLE
implement reference values for turbine/wind parameters

### ISSUE THREAD

**Issue by bayc** [NREL/floris#517]
Need to implement input structure and processing of reference values and user-defined values. These include: tilt, floater motion, potentially TI? Can implement similar to reference air density value recently added.

- [x] tilt
- [ ] floater motion
- [ ] TI?

Figure out which reference properties should be scalar, or support vectors

**Comment by misi9170** [comment]
@bayc , what is the status of this one? Is this related to the multidimensional Cp/Ct table effort?

**Comment by rafmudaf** [comment]
Bump @bayc
