### ISSUE TITLE
Function make_wind_rose_from_weibull of WindRose returns unnecessary dataframe

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#534]
The function make_wind_rose_from_weibull within the WindRose class returns a dataframe, which confuses it's main purpose of updating the member df of the class.  Propose to delete the return lines

### Discussed in https://github.com/NREL/floris/discussions/529

<div type='discussions-op-text'>

<sup>Originally posted by **JarneVB** November 14, 2022</sup>
I tried calculating the farm AEP with a wind rose by using get_farm_AEP_wind_rose_class, but I get the following error message: 
> 'DataFrame' object has no attribute 'df'

It is about these lines:

       wind_speeds_wind_rose = wind_rose.df.ws.unique()
       wind_directions_wind_rose = wind_rose.df.wd.unique()
       self.reinitialize(wind_speeds=wind_speeds_wind_rose, wind_directions=wind_directions_wind_rose)
       # Build the frequency matrix from wind rose
       freq = wind_rose.df.set_index(['wd','ws']).unstack().values`

It looks like df is defined nowhere. How can I fix this?</div>

**Comment by misi9170** [comment]
@paulf81 , now that we handle wind roses differently in v4, has this been addressed?

**Comment by paulf81** [comment]
Yeah, I think this can be closed as just basically out-dated
