### ISSUE TITLE
Add turbine weights to the function get_farm_AEP_wind_rose_class

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#540]
**Is your feature request related to a problem? Please describe.**
Related to discussion #529 , would like to supply turbine_weights to the function get_farm_AEP_wind_rose_class to enable modeling turbines not included in power calculation

**Describe the solution you'd like**
Since get_farm_AEP_wind_rose_class calls get_farm_AEP and this function already accepts turbine_weights, should just be a matter of chaining the weights through

**Comment by rafmudaf** [comment]
Closed by #541
