### ISSUE TITLE
Add new model of wake subjected to veered inflow

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#545]
**Is your feature request related to a problem? Please describe.**
A new analytic model has been published which can model wake steering in the precense of veer. 

https://www.mdpi.com/1996-1073/15/23/9135
 
Creating this issue to propose including into FLORIS (@bayc you and I discussed already, no rush, just wanted to put a "pin" so I don't forget now that is published)

**Comment by rafmudaf** [comment]
@paulf81 I think this issue is a duplicate of #520. If that's right, could you close one?

**Comment by paulf81** [comment]
Yes you are right, closing because it is a duplicate of #520
