### ISSUE TITLE
WindMap: Invalid check for Numpy array values

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#55]
Passing a `np.array` to WindMap for the `wind_speed` or `wind_direction` arguments results in a `ValueError` even though these are valid values.

The correct logic may be to check for `not None`.

Edited 2/11/2020 by @rafmudaf

**Comment by rafmudaf** [comment]
@paulf81 could you point me to the line you're referring to? I don't see a comparison at line 54 in Wind Map for whether the input is a list or None. There's this:

```
        if wind_direction:
            self.calculate_wind_direction()
```

but that should pass as long as the input is not None, False, or 0.

**Comment by paulf81** [comment]
When I pass in an np.array it excepts and says that the logic is ambiguous, did I mean to use "any" or "all"?  Something like that,

**Comment by rafmudaf** [comment]
Well it looks like Python handles lists and Numpy arrays differently. I guess its not surprising, but still surprising.

```
(floris) >>mbp@~/Development/floris (docs *$)$ python
Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> l = [1,2,3]
>>> if l: print('1')
... 
1
>>> import numpy as np
>>> npl = np.array([1,2,3])
>>> npl
array([1, 2, 3])
>>> if npl: print('1')
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> if [0,1,0,1]: print('1')
... 
1
>>>
```

**Comment by paulf81** [comment]
I had this issue crop up in some of my stuff, we used this function (I think we wrote together)
def _convert_to_numpy_array(series):
    if hasattr(series, 'values'):
        return series.values
    elif isinstance(series, np.ndarray):
        return series

To guard against series being applied accidentally instead of an np.array, could re-write to detect if it is an np array, convert to list like

def _convert_to_list(series):
    if hasattr(series, 'tolist'):
        return series.tolist()
    elif isinstance(series, list):
        return series

Or something?  Or just re-writing the code so it's happy with either?

**Comment by rafmudaf** [comment]
I say lets to do the latter... avoid type checking and change the if-statements instead
```
        if wind_direction is not None:
            self.calculate_wind_direction()
        if wind_speed is not None:
            self.calculate_wind_speed()
        if turbulence_intensity is not None:
            self.calculate_turbulence_intensity()
```

These arguments are ultimately converted to `np.array` later on, so I think its best to let Python raise an exception when it cant get the duck to quack.

**Comment by rafmudaf** [comment]
Won't fix since this is reworked in https://github.com/nrel/floris/tree/v3
