### ISSUE TITLE
Turbine power not flat above rated

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#554]
**Bug description**
Not sure it's an important bug, but it could be a problem for optimizers that the power of turbines is not flat wrt changes in wind speed above rated, but wiggles a little bit.  We tried to cut this down by interpolating on power and not cp, but some non-flatness is still evident

**To Reproduce**
Run the example python 18_check_turbine.py 
For the 5MW plot, zoom in on rated power
![image](https://user-images.githubusercontent.com/6117702/211097479-402061ec-ca6d-4bf6-aa6b-0e4255c6d671.png)

**Expected behavior**
I think this should be perfectly flat.  I can imagine how to do this, but what I have come up with so far would incur some time penalty so I don't have an idea I yet like so just leaving this issue to mark it

**Floris Version**
3.2

**Comment by paulf81** [comment]
I think this issue is leading other problems (see Discussion #583 for example problems), maybe should get advanced toward a solution.  

One thought I had is that if we switched from specifying power in terms of Cp, over to Power, we can guarantee, this flatness.  But that might make scaling by rotor area less convenient.  

Maybe a solution would be to add some sort of check at the point we compute inner power in turbine.py

        inner_power = (
            0.5 * self.rotor_area
            * self.fCp_interp(wind_speeds)
            * self.generator_efficiency
            * wind_speeds ** 3
        )

Maybe to not allow differences below some threshold?  Like start from the highest wind speeds, and insist that if the next lowest wind speed is only different by some negligible amount, then force it to be the same?  I don't think this would impact compute time since it would be done at instantiation of the turbine object?  @Bartdoekemeijer @bayc @rafmudaf any thoughts?  I could test it out if you think it's in the right direction

**Comment by rafmudaf** [comment]
I wonder if this would be better handled by "fixing" the input data rather than adding a check in the computation to handle an edge case. For example, the power curve could be smoothed in a preprocessing step.

**Comment by paulf81** [comment]
I had an idea this morning that we could have the user fix out to 8-9 decimal places and then have FLORIS throw an error if the resulting curve isn't monitonic, but there would be a problem if the power curve really did ramp down at higher wind speeds

**Comment by paulf81** [comment]
Closing this as can say resolved by PR #590

**Comment by rafmudaf** [comment]
After additional discussion, we've concluded that this is *not* resolved by #590, and a more appropriate solution is to require that users define power instead of Cp for the turbine performance curve.

**Comment by misi9170** [comment]
Working on this now in the context of moving to specifying power (rather than Cp) for v4.

**Comment by rafmudaf** [comment]
> Working on this now in the context of moving to specifying power (rather than Cp) for v4.

Heads up that this is partly enabled in #762. We should finalize that pull request first and then finish up the transition from Cp to Power.

**Comment by misi9170** [comment]
Added check for this in turbine_utilities in #765 , which will be used when converting v3 models to v4. Check could also be run on instantiation of the `FlorisInterface`, if we'd like.

**Comment by paulf81** [comment]
This issue is resolved (in v4) by #784
