### ISSUE TITLE
Actions completion time degraded after #555

### ISSUE THREAD

**Issue by rafmudaf** [NREL/floris#563]
### Bug description
This isn't exactly a bug, but it is a degradation in performance. Since #555, the [Check Examples API](https://github.com/NREL/floris/actions/workflows/check-working-examples.yaml) workflow in GitHub Actions takes about 11 minutes to complete whereas it finished in around 5 minutes before. This is expected since the new example included in #555 takes a few minutes to run the calculation.

One possible improvement to that workflow is to run the examples in parallel. Another option is to reduce the computation included in the example from #555.

**Comment by rafmudaf** [comment]
@Bartdoekemeijer what do you think about reducing the computation cost in the example through something like increasing the step size for the wind rose?

**Comment by Bartdoekemeijer** [comment]
Good catch! I had no idea this would pose an issue. How about:

1. Set `N=4` or `N=3` in line 35 to go from 25 to 16 or even 9 wind turbines in the `FlorisInterface` object.
2. Set `wind_directions = np.arange(0.0, 360.0, 3.0)` to go from 360 to 120 wind directions.
3. Set `wind_speeds=np.arange(1.0, 25.01, 1.0)` to go from 30 to 25 wind speeds.

On my local machine with one worker, the entire example with `N=4` takes about 3 minutes to complete. With 16 workers, the entire example takes about 30 seconds to complete. With `N=3`, these numbers are 30 seconds and 12 seconds, respectively.

Generally, I'm hesitant to go to a coarser resolution in the wind rose than 3 deg steps. I feel like many users just take an example, modify it to their wind farm, and leave the default settings assuming they are representative of how actual yield calculations should be done. Hence, I'd like to keep a realistic wind rose resolution.

**Comment by rafmudaf** [comment]
@Bartdoekemeijer I change N to 4 for 16 turbines and reduced the max wind speed to 25 in #569. Now the workflow completes in 7-8 minutes which is pretty close to the 5-6 minutes that it was before. Thanks for your input here.
