### ISSUE TITLE
Bug report - new TI sorting bugfix not compatible with fi.calculate_no_wake

### ISSUE THREAD

**Issue by mr483** [NREL/floris#572]
**Bug description**
Hi @bayc, I was just testing this bug fix out locally and found that it causes a numpy error when I try running fi.calculate_**no_wake**():

The error occurs at the new line in finalize in flow_field.py: 
```
    def finalize(self, unsorted_indices):
        self.u = np.take_along_axis(self.u_sorted, unsorted_indices, axis=2)
        self.v = np.take_along_axis(self.v_sorted, unsorted_indices, axis=2)
        self.w = np.take_along_axis(self.w_sorted, unsorted_indices, axis=2)

        self.turbulence_intensity_field = np.mean(np.take_along_axis(self.turbulence_intensity_field_sorted, unsorted_indices, axis=2), axis=(3,4))
```

IndexError: index 3 is out of bounds for axis 2 with size 1

The array self.turbulence_intensity_field_sorted attains the correct dimension in the code in the solver, but of course if no wake calculations are performed then this never occurs. 

My ugly fix was just the following (I check the turbine axis and if it still only has a length of 1 I assume a no-wake calculation was performed): 
```
        if self.turbulence_intensity_field_sorted.shape[2]!=1:
            self.turbulence_intensity_field = np.mean(np.take_along_axis(self.turbulence_intensity_field_sorted, unsorted_indices, axis=2), axis=(3,4))
```

**Comment by rafmudaf** [comment]
In addition to addressing this bug, we should add a unit test for `FlorisInterface.calculate_no_wake` to catch these situations in the future.
