### ISSUE TITLE
Setting non-rectangular boundaries for layout optimization

### ISSUE THREAD

**Issue by bayc** [NREL/floris#575]
### Discussed in https://github.com/NREL/floris/discussions/557

<div type='discussions-op-text'>

<sup>Originally posted by **Rodrig03** January 18, 2023</sup>
Hello, 

Im running layout optimization tests using LayoutOptimizationScipy from floris.tools.optimization.layout_optimization.layout_optimization_scipy

I am experiencing issues setting irregular wind farm boundaries. It appears that a the most outer "x" and "y" coordinates are taken to create a new rectangle boundary, which is then used for the optimization. 
For example, when setting the following boundaries = [(0, 0), (0, 1600), (1000, 1600), (1600, 1200), (1600, 0), (0, 0)] I get the results shown in the image.
![Figure_4](https://user-images.githubusercontent.com/122991766/213195440-9667ea3f-a32b-4472-b3fc-5eff3c54ae82.png)

Is there any way to set irregular boundaries based on "x", "y" coordinates for layout optimization?
</div>

**Bug description**
As mentioned above, the boundary constraint is not respected in the Scipy layout optimization tool. The issue lies in how the boundary constraint is formulated, such that the distance from the boundary is always positive, which is interpreted by Scipy as satisfying the constraint.

**To Reproduce**
1. Run example `15_optimize_layout.py` on the current `main` branch of FLORIS with the following boundaries:
```
boundaries = [(0, 0), (0, 1600), (1000, 1600), (1600, 1200), (1600, 0), (0, 0)]
```

**Expected behavior**
The final turbine locations should all be within the boundaries.

**Screenshots, if applicable**
See above referenced discussion.

**Floris Version**
3.2.2

**Comment by rafmudaf** [comment]
@bayc this may be ready to close since #576 is merged.
