### ISSUE TITLE
Implement the v2 capability of calculating/returning wind speed values from specified points in the flow field

### ISSUE THREAD

**Issue by bayc** [NREL/floris#585]
**Is your feature request related to a problem? Please describe.**
In FLORIS v2, the users could supply a set of points to `calculate_wake` to have the wake model executed at.

**Describe the solution you'd like**
I'd like to see a similar functionality developed for FLORIS v3.

**Describe alternatives you've considered**
Continue using v2, but this isn't desired.

**Additional context**
None currently.

**Comment by rafmudaf** [comment]
An alternative that might be considered is to add turbines as points to be calculated but not add their effect into the flow field. This is the same as done in the visualization method introduced in #418.

**Comment by rafmudaf** [comment]
This was introduced in #650
