### ISSUE TITLE
High wind speed issue

### ISSUE THREAD

**Issue by Maartenvbeek** [NREL/floris#59]
**Bug description**
When running FLORIS with 5 or more aligned NREL5MW turbines (spacing 3D and higher) , gives issues when the wind speed is high. The model returns a 'nan' power production instead of (near) rated power for the last downstream turbine(s) for wind speeds 23 m/s and higher (Ct<0.07). 

The model does return runtime warnings, and the issue occurs because at high wind speeds the thrust coefficient is low. Therefore a low velocity deficit is present. That combined with shear in the wind speed results in a negative velocity deficit (so velocity increase). At some point the squareroot is taken of this negative velocity deficit, resulting (probably) in complex numbers which the FLORIS model is not able to handle. This happens in floris/simulation/wake_deflection.py, line 242:
`ln_deltaNum = (1.6 + np.sqrt(M0)) * (
            1.6 * np.sqrt(sigma_y * sigma_z /
                          (sigma_y0 * sigma_z0)) - np.sqrt(M0))`
So in this line 'M0' contains negative values.

**To Reproduce**
The code is taken from example 5 of FLORIS and adjusted to increase the number of aligned turbines and increase the wind speed. 21 m/s is shown in comparison, because at that wind speed FLORIS returns rated power instead of 'nan'.

```
import matplotlib.pyplot as plt
import floris.tools as wfct
import floris.tools.visualization as vis
import floris.tools.cut_plane as cp
import numpy as np
from mpl_toolkits.axes_grid1 import make_axes_locatable, axes_size

# Initialize FLORIS model
fi = wfct.floris_utilities.FlorisInterface("example_input.json")

# set turbine locations to 5 turbines in a row - demonstrate how to change coordinates
D = fi.floris.farm.flow_field.turbine_map.turbines[0].rotor_diameter
nD = 3
layout_x = [0, nD*D, 2*nD*D, 3*nD*D, 4*nD*D]
layout_y = [0, 0, 0, 0, 0]
fi.reinitialize_flow_field(layout_array=(layout_x, layout_y),wind_speed=21)

# Calculate wake
fi.calculate_wake()
print(fi.get_turbine_power())

fi.reinitialize_flow_field(layout_array=(layout_x, layout_y),wind_speed=23.5)

# Calculate wake
fi.calculate_wake()
print(fi.get_turbine_power())
```

**Expected behavior**
For these high wind speeds I expect the turbines to operate at rated power and hence return rated power instead of a 'nan' value.

**Floris Version**
Version 1.0.0 - installed through pip about a week ago.

**Comment by bayc** [comment]
This is fixed in FLORIS v3.0. Thank you for the feedback!
