### ISSUE TITLE
Horizontal cut plane fails with user-specified resolution and bounds

### ISSUE THREAD

**Issue by ewquon** [NREL/floris#61]
**Bug description**
Resulting visualization from calling `wfct.visualization.visualize_cut_plane()`

**To Reproduce**
```
fi =  wfct.floris_interface.FlorisInterface('asdf.json')
fi.calculate_wake()
Nx,Ny = 301,201
hor_plane = fi.get_hor_plane(x_resolution=301, y_resolution=201, 
                             x_bounds=(-5,10), y_bounds=(-5,5))
fig, ax = plt.subplots()
wfct.visualization.visualize_cut_plane(hor_plane, ax=ax)
```
![debug](https://user-images.githubusercontent.com/18267059/74790538-14182780-5275-11ea-8d47-b48999e4aa37.png)

**Expected behavior**
Manually sorting and plotting the data:
```
df = hor_plane.df.set_index(['x1','x2','x3']).xs(1.0,level='x3').sort_index()
x1 = df.index.get_level_values(0).values.reshape((Nx,Ny))
x2 = df.index.get_level_values(1).values.reshape((Nx,Ny))
u = df['u'].values.reshape((Nx,Ny))

fig,ax = plt.subplots()
cm = ax.pcolormesh(x1,x2,u, cmap='magma')
ax.axis('scaled')
fig.colorbar(cm, ax=ax)
fig.savefig('u_{:s}.png'.format(case),bbox_inches='tight')
```
![u_CT095](https://user-images.githubusercontent.com/18267059/74790617-5b061d00-5275-11ea-939a-46a23241f082.png)

**Floris Version**
commit 2833cc7bc952aa7c5d66963a749ad71900d345ab

**Comment by paulf81** [comment]
Thanks for reporting!  Could I just ask which branch?

**Comment by NilsGaukroger** [comment]
Using the develop branch. I’ve realised there is now a subfolder for Optimization examples but I am also having issues running those, I get a ModuleNotFoundError for “pyoptsparse”.

Thanks for the quick reply.

Nils

**Comment by ewquon** [comment]
develop

**Comment by paulf81** [comment]
ok, I submitted a pull request, would you check this:
https://github.com/NREL/floris/pull/64

I believe the DF needed one additional sort to avoid this sort of scrambling, also, the bounds should be in meters, this wasn't said anywhere so I added some comments, but probably this could still be much clearer, thanks for reporting the bug!!

**Comment by ewquon** [comment]
I've approved the PR. Thanks!
