### ISSUE TITLE
Feature request: Multi-dimensions on cp/ct lookup

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#619]
# Allow multi-dimensional inputs on Cp/Ct lookup

This issue is to capture the desire that the turbine Cp/Ct lookup expand to multiple-dimensions (in addition to wind speed).  Possibilities include turbulence intensity, wave height/period.  This higher DOF LUT will allow Cp/Ct to respond to changes in inflow besides wind speed.

Connected to this request we also consider providing some sort of pre-processing tool which could built out a wind speed only Cp/Ct into other dimensions using some simple heuristics.

**Comment by paulf81** [comment]
Adding comment that this could also be a means to include curtailment if we include multiple cp/ct tables for various curtailment settings (or boosted on the other side) and have a parameter to select from them

**Comment by paulf81** [comment]
@bayc implementing this initially via x-ray

**Comment by rafmudaf** [comment]
@paulf81 @bayc is this issue addressed?

**Comment by rafmudaf** [comment]
> Connected to this request we also consider providing some sort of pre-processing tool which could built out a wind speed only Cp/Ct into other dimensions using some simple heuristics.

Is this part available?

**Comment by bayc** [comment]
The initial capability is implemented now. I am not sure about the pre-processing tool, is this something we still want to add @paulf81 ?

**Comment by paulf81** [comment]
I would set aside the pre-processing tool for the moment, and maybe we re-add it as the expanded WindRose tool comes into view, thanks for checking @bayc !
