### ISSUE TITLE
Feature request: Implement yaw optimization via geometric relationship

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#621]
# Implement yaw optimization via geometric relationship
Incorporate the rapid yaw optimziation approach descibed in PJ Stanley's paper here:

https://wes.copernicus.org/preprints/wes-2023-1/

Believe @bayc  has approach ready to implement

@pjstanle FYI

**Comment by misi9170** [comment]
I'm working on this and will have a pull request up in the next few days.

**Comment by misi9170** [comment]
Closed by #681
