### ISSUE TITLE
Small power gain to yaw under high speeds

### ISSUE THREAD

**Issue by cibeah** [NREL/floris#629]
Hello, 

Working on a case with high speeds (> 12m/s), I have noticed an unexpected increase in power output as the yaw error increases. 

## How to reproduce
Running `18_check_turbine.py` for a single turbine  with `wind_speed_to_test_yaw=8` gives a smooth curve:

![8ms](https://user-images.githubusercontent.com/33727915/234055688-206f6701-b93a-4eb8-9db8-824c6b2a5710.png)

But at `wind_speed_to_test_yaw=15`, the same script gives:

![15ms](https://user-images.githubusercontent.com/33727915/234055719-830f3302-4317-4162-ba42-65ae2b33f684.png)

This seems very similar to #340, which has been solved by #341 and closed. It seems that some inconsistencies remained, although at very small magnitudes (at the order of the Watt). This mostly poses a problem when doing yaw optimization: 

I ran `10_opt_yaw_single_ws.py` for a yaw optimization routine with `wind_speeds=[15.0]` and obtained this, similar to #340 despite the fix. 

![yaw_opt](https://user-images.githubusercontent.com/33727915/234055751-3c01458f-233e-42e4-8460-9f19b58ecd18.png)

Thank you very much !

## Floris version
v3.3
I noticed this behaviour on both the installation done with PyPi and an installation done from the source code cloned today.

## System Information
 - OS: Windows

**Comment by paulf81** [comment]
This is now fully addressed in v4 via pull request #765 and #784
