### ISSUE TITLE
Support for turbulence intensity field

### ISSUE THREAD

**Issue by maapasan** [NREL/floris#666]
# Manage turbulence intensity arrays in FlorisInterface.reinitialize

While wind speed or wind direction are defined using arrays (which allow the simultaneous simulation of several wind inputs), the turbulence intensity is defined as float.

In FLORIS, turbulence intensity is established for all combinations of direction and speed.

However, the turbulence intensity values are dependent on wind speed (turbulence intensity decrease with wind speed in real operating conditions). 

## Proposed solution
Update implementation in order to be able to run the simulations with array input turbulence intensity 
These changes will include the definition of turbulence_intensity in FlowField, as it is defined as float and it is needed NDArrayFloat, similar to wind_speeds and wind_directions.

## Additional context
Current use of the function, where wd and ws are np.array with same shape
`fi.reinitialize(wind_directions=wd, wind_speeds=ws, time_series=True)`
Suggested use (wd, ws and ti are np.array with same shape
`fi.reinitialize(wind_directions=wd, wind_speeds=ws, turbulence_intensity= ti, time_series=True)`

Thank you very much!!!

**Comment by paulf81** [comment]
A good suggestion @maapasan , I'm adding some tracking info and we'll put it on the agenda for v3.5

**Comment by paulf81** [comment]
@bayc , is this something you've looked at before?

**Comment by paulf81** [comment]
I hope to address this request in #775

**Comment by paulf81** [comment]
Now connecting to Issue #778
