### ISSUE TITLE
Bug report - GCH with fixed 0.12 shear coefficient

### ISSUE THREAD

**Issue by fg320** [NREL/floris#675]
# GCH: calculations have fixed 0.12 shear coefficient
 First of all, thank you for the great code. I wanted to point out a missing link in the GCH calculations. In the "simulation/wake_deflection/gauss.py" file, the GCH calculations for vel_top and vel_bottom have a fixed shear exponent of 0.12. This should be adjustable and directly connected to the input wind shear. This can be found in the following methods:

- wake_added_yaw
L285 ```vel_top = ((HH + D / 2) / HH) ** 0.12 * np.ones((1, 1, 1, 1, 1))```
L294 ```vel_bottom = ((HH - D / 2) / HH) ** 0.12 * np.ones((1, 1, 1, 1, 1))```

- calculate_transverse_velocity
L383 ```vel_top = ((HH + D / 2) / HH) ** 0.12 * np.ones((1, 1, 1, 1, 1))```
L392 ```vel_bottom = ((HH - D / 2) / HH) ** 0.12 * np.ones((1, 1, 1, 1, 1))```

Thank you.

## Floris version
 FLORIS V3.4

**Comment by rafmudaf** [comment]
Hi @fg320 Thank you for catching and reporting this. Are you able to make this change and submit a pull request?

**Comment by rafmudaf** [comment]
Some guidance for contributing is available in the [Developer's Guide](https://nrel.github.io/floris/dev_guide.html), and I'm curious if there's anything else that would make the process more clear.

As for the code change, the input wind shear is stored on the `FlowField` object, and this is accessible within the various solver functions that use `wake_added_yaw`. Like you suggest, a new input argument should be added to `wake_added_yaw` to take the wind shear from the solvers.

**Comment by fg320** [comment]
Hi @rafmudaf, thank you for the reply and the guidelines. The Developer's Guide was clear and useful. There was not anything missing in my opinion. I have made the changes and submitted a pull request #679. Thanks!
