### ISSUE TITLE
Allow ParallelComputingInterface to support time_series mode

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#707]
### Discussed in https://github.com/NREL/floris/discussions/705

<div type='discussions-op-text'>

<sup>Originally posted by **paulf81** September  1, 2023</sup>
Question for @rafmudaf  and @Bartdoekemeijer , does ParallelComputingInterface support time_series mode?  Is it just a matter of passing the flag through, or would this break something I'm missing?
</div>

Based on discussion #705 , this should be a fairly straightforward change to explicitly support time_series (it may already work but we haven't tested).  But at any rate the relevent flags should be passed through.   We could also add an example for syntax

**Comment by paulf81** [comment]
I think this is implicitly handled in the conversion to 4.0, @rafmudaf / @misi9170 agree?  Think we can close

**Comment by rafmudaf** [comment]
I suggest we wait to close it until there's a replacement issue or card to cover this within the v4 project.

**Comment by paulf81** [comment]
One down

**Comment by paulf81** [comment]
I was thinking we close this as an issue and have a new issue that is "parallelinterface works in 4.0" but that is where I got stuck as, that would have to be true?  @rafmudaf what do you think?
