### ISSUE TITLE
Feature request: Ambient TI as a function of wind direction and wind speed

### ISSUE THREAD

**Issue by Bartdoekemeijer** [NREL/floris#713]
# Feature request: turbulence_intensity as a function of wind direction and wind speed
The industry typically evaluates the annual energy production of a site by using a wind rose of the site, specifying the frequency of each combination of wind direction and wind speed. Additionally, we are often provided one ambient turbulence intensity value for each of those wind direction/speed bins. Alternatively, we may be given a wind-speed vs. turbulence intensity curve, showing that turbulence is high at low wind speeds, and much lower at high wind speeds. FLORIS only allows us to insert one turbulence value for the entire wind rose. With a relatively small change, I think we could update this and provide this very useful functionality.

## Proposed solution
Allow users to insert two-dimensional table for `turbulence_intensity`, which matches the dimensions `(n_wind_directions, n_wind_speeds)`.

## Alternatives considered
One can also simply apply a for-loop over each wind direction and wind speed and apply the relevant TI for each bin, but that completely beats the purpose of the refactorizations of FLORIS v3.

## Additional context
I have written up a preliminary solution that I'll post over in the PR section.

**Comment by maapasan** [comment]
Hello @Bartdoekemeijer 

I agree with you, turbulence intensity is a significant characteristic and it is related with the wake simulation (basis of FLORIS).
I sent an issue that I think that is totally related with your suggestion. https://github.com/NREL/floris/issues/666

Kind regards from CENER :)

**Comment by Bartdoekemeijer** [comment]
Ah of course, @maapasan! Thanks for highlighting that! I'm becoming a bit lazy and not searching the existing Issues like I should have! Will leave my Issue here but will link yours too in my PR.

**Comment by paulf81** [comment]
Plan to address this is in #775

**Comment by paulf81** [comment]
now connecting to Issue #778

**Comment by paulf81** [comment]
@Bartdoekemeijer , if you have a chance, have a look at #782 which I think addresses this issue

**Comment by paulf81** [comment]
@Bartdoekemeijer #782 is now in review if you want to have a look to make sure this does what you wanted

**Comment by paulf81** [comment]
This is included in v4 via #782
