### ISSUE TITLE
Change dependent versioning to semantic versioning using the compatible release specifier

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#745]
Improve dependencies to use compatible release specifier such that the dependencies won't go up a major version unless intentionally changed in an update to this repo.  This is to avoid breaks due to API changes.  Info on compatible release specifier:

https://packaging.python.org/en/latest/specifications/version-specifiers/#id4

**Comment by rafmudaf** [comment]
@paulf81 I'm on board with adding version specificity to the dependency libraries for FLORIS. The documentation for the [compatible release specifier](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release) states:
> This operator MUST NOT be used with a single segment version number such as ~=1.
This rules out using it to maintain a major version number. To achieve that constraint, though, I think we can use a combination of the [inclusive ordered comparison](https://packaging.python.org/en/latest/specifications/version-specifiers/#inclusive-ordered-comparison) and [exclusive ordered comparison](https://packaging.python.org/en/latest/specifications/version-specifiers/#exclusive-ordered-comparison), such as:
```python
numpy>=1,<2
```

**Comment by paulf81** [comment]
I think compatible release covers us, the documentations says these are equivalent:

![image](https://github.com/NREL/floris/assets/6117702/8a3864b8-e80d-4c39-a05f-9efb105fa6bb)
