### ISSUE TITLE
Raise informative error if v3 intput yaml passed into v4

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#791]
This issue is to catch the intention that before releasing v4 the following enhancement should be included, although it's final form will depend upon the final form of v4.  FLORIS v4 should raise an informative error when a v3 input yaml file is passed into v4.   Current issues to detect are:

- Cp values passed in in place of Power
- Tubulence Intensity instead of turbulence intensities

However recommend a full reassessment toward the end of the v4 development process.

Alternaitively or additionally, we can provide an automatic converter script from v3 to v4

**Comment by misi9170** [comment]
Closed by #829
