### ISSUE TITLE
Use correct turbine names in plots

### ISSUE THREAD

**Issue by aclerc** [NREL/floris#804]
I was just discussing this with @paulf81 and he encouraged me to add an issue :)
Please can any plots showing turbine names use the correct turbine names. For example in the farm shown below the turbines are actually named T02, T04, T05, etc. but T00, T01, T02, etc. is displayed. If the correct turbine names are not available using the name "T00" will probably never be right, so if you have to fall back to generated names I would at start with T01
![image](https://github.com/NREL/floris/assets/9821851/0496ef07-5ec9-46c1-8e49-74f97f6a8a60)

**Comment by aclerc** [comment]
sorry looks like my screenshot is too fuzzy to read but @paulf81 can add the original image if needed!

**Comment by rafmudaf** [comment]
@aclerc can you share more information so that we can recreate this issue? A simplified analysis script including the functions you used for plotting would be helpful. Also, which version of FLORIS are you using?

**Comment by paulf81** [comment]
Believe this issue is resolved by #805
