### ISSUE TITLE
[Bug] Update parallel interface to work with uncertainty interface

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#834]
# Update parallel interface to work with uncertainty interface

Working my way through #830  I noticed that parallel_computing_interface.py still has functions set for the old uncertainity_interface, wanted to flag this should be fixed with some steps:

- [x] Make sure we still want the names parallel_computing_interface and uncertainity_interface given #830 
- [x] Add test of parallel_computing_interface + uncertainity_interface
- [x] Update calls (don't use unc_pmfs for example)

**Comment by misi9170** [comment]
Closed by #830
