### ISSUE TITLE
Missing folder sampling/ with blockMesh for sowfa_example

### ISSUE THREAD

**Issue by DeeDiveT** [NREL/floris#90]
Hi, I'm trying to run turbine example `sowfa_example`.

Errors occurred with `blockMesh` in `runscript.preprocess` ,(see https://github.com/NREL/floris/blob/6b0a7ad3aec9d92ec7a5fff01df2a3864fb67c83/examples/sowfa_comparisons/sowfa_example/system/controlDict#L58), which gives `file not found` error for `system/sampling/sliceDataInstantaneous`.

It seems that the given `sowfa_example` does not have the required directory, while other examples in sowfa all have the `system/sampling` directory. Is there anyone who has some ideas to solve this problem and could kindly help me? 
Millions of thanks in advance.

**Comment by paulf81** [comment]
Hi,

  Sorry for the confusion, that folder is only an example containing outputs from SOWFA to read into FLORIS, not a complete case to run, this would probably be too much to include within FLORIS.  The main idea was just show how to import SOWFA outputs for comparison with FLORIS.  I realize now that’s not clear, and we can try to document that better.

  Are you trying to run SOWFA?  I recommend trying the examples which are included with the SOWFA repository, do those work for you?

Paul

**Comment by DeeDiveT** [comment]
Hi @paulf81, thanks for your reply. Yes, I'm trying to run SOWFA, but it seems that default examples in SOWFA, namely `example.ALM` and `example.ADM`, contain many bugs and do not work properly. I find that FLORIS also has the processing utilities for SOWFA outputs, and I thought it would also be an example of SOWFA, tweaked by you.
Do you have some suggestions about how to run experiments with `SOWFA`, particularly for windfarms?

Best

**Comment by DeeDiveT** [comment]
Hi @paulf81, I tried running a sowfa example, and when I use the floris utility to process the output by sowfa, it seems that there is no folder called `array_mean` and file `array.mean0D_UAvg.vtk`.

Could you please tell me how to generate that vtk file? Thanks.

**Comment by rafmudaf** [comment]
@paulf81 these VTK files should be generated by SOWFA, correct? Seems like this is a SOWFA-specific question.

**Comment by paulf81** [comment]
I put this function into my controlDict.1 file:

array.mean
    {
          type                sets;
          functionObjectLibs ("libSOWFAsampling.so" "libSOWFAfileFormats.so");
          enabled             true;
          interpolationScheme cellPoint;
          outputControl       timeStep;
          outputInterval      250;
          setFormat           vtkStructured;
          fields
          (
              UAvg
              uuPrime2
              p_rgh
              p_rghAvg
          );

          sets
          (
              array.mean0D
              {
                  type                 arrayStructured;
                  axis                 xyz;
                  origin              (498.0005 200.001 0.001);
                  coordinateRotation
                  {
                        type           axesRotation;
                        e1            (1 0 0);
                        e2            (0 1 0);
                  }
                  pointsDensity       (451 141 31);
                  spanBox             (4500 1400 300);
              }
          );
    }

(You'll adjust to your particular simulation) but it produces a VTK output as a regular grid.  In this case it produces on every 250s and I copy the last one made into array_mean
