### ISSUE TITLE
Precision errors cause bug on Windows

### ISSUE THREAD

**Issue by pduff-code** [NREL/floris#91]
**Bug description**
AttributeError: module 'numpy' has no attribute 'float128' coming from line 112 in floris\simulation\wake_velocity\gaussianModels\gauss.py - seems to be Windows specific based on:
https://github.com/winpython/winpython/issues/613
https://stackoverflow.com/questions/9062562/what-is-the-internal-precision-of-numpy-float128

Changing 'np.float128' to 'np.longdouble' seems to fix the problem for me.

**To Reproduce**
-Run a flow case or AEP calculation using the gauss wake model on Windows

**Expected behavior**
Run the flow case/ AEP calculation.

**Screenshots, if applicable**
![ecd4c80c-3ded-4777-8eab-a75cbcf79a8b](https://user-images.githubusercontent.com/57646223/79162587-cd3d3e80-7d9a-11ea-9ce3-60545cb268b9.jpg)

**Floris Version**
FLORIS 1.1.7 on the develop branch

**System Information (please complete the following information):** 
Windows 10
(I was using VS Code)

(My first github issue so let me know what other information is needed if something is missing)

**Comment by rafmudaf** [comment]
Thanks for reporting this @pduff-code. Like you mentioned, we can't fix the problem that Numpy doesn't support that data type on Windows, but we should understand why such a large precision is needed in the first place.

**Comment by bayc** [comment]
This is no longer an issue in FLORIS v3.0.
