### ISSUE TITLE
Add 3rd dimension to HeterogeneousMap

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#910]
# Add 3rd dimension to HeterogeneousMap

On original submission of HeterogeneousMap, I neglected to include a capability for 3rd (z) dimension, although this is already supported by the underlying heterogeneous_inflow_config dictionary.  Starting an issue to track this issue and list out intended improvements

## Proposed solution
Proposed solution should include:

  1) Z-term optionally included in HeterogeneousMap and routed through each member function
  2) Function to build a new 2D HeterogeneousMap via composition and return it
  3) Function to visualize 3D heterogeneity (maybe, if not too complicated)
  4) Function to show apparent shear layer
  5) Updated testing
  6) Update documentation

And then I plan to fold-in some additional improvements I've realized I should have originally included:

  7) Functions to provide statistics of HeterogeneousMap, including outliers, to help screen potential issues
  8) Functions to return subset HeterogeneousMap by wind direction and wind speed, also by composition

@misi9170 , just wanted to flag this to you, I'll do the work but just making sure you agree with this list, or if you think of any additions or subtractions

**Comment by misi9170** [comment]
Addressed by #915
