### ISSUE TITLE
Add WRG file reader to FLORIS

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#916]
# Add WRG file reader to FLORIS

WRG files, wind resource grids, are used in industrial practice for describing how wind resources vary over a given site.  WRGs represent wind resources by the parameters of Weibull distributions for given grid points and given wind directions sectors.  This implies that different points in the site will have different wind rose distributions.

### Information on WRG files:

https://backend.orbit.dtu.dk/ws/portalfiles/portal/116352660/WAsP_10_Help_Facility.pdf

## Proposed solution

We propose to develop new modules that:

- Read and hold the information embedded in a WRG file
- Develop a new WindRoseByTurbine class that holds a separate wind rose per turbine in a farm
- Modify FlorisModel (and children) to accept WindRoseByTurbine and provide  `get_expected_turbine_power()` and change how `get_expected_farm_power()` operates when WindRoseByTurbine is provided
- Investigate how best to perform layout optimizations under these conditions

@misi9170 @pjstanle

FYI: @ejsimley @rafmudaf @bayc

**Comment by misi9170** [comment]
#919 addresses this
