### ISSUE TITLE
Allow more recent versions of `coloredlogs` as a dependency to FLORIS

### ISSUE THREAD

**Issue by pjireland** [NREL/floris#938]
# Allow more recent versions of `coloredlogs` as a dependency to FLORIS
In `floris/setup.py`, `coloredlogs` is currently pinned to version `~=10.0`. This version is quite old now (release was May 2018). 

## Proposed solution
Recommend either switching to a newer version (the latest is `15.0.1`, released in June 2021) or allowing any version greater than or equal to `10.0`.

## Additional context
I'm trying to install FLORIS within an environment that requires `coloredlogs==15.0.1`. I therefore need to create my own branch of FLORIS (with the `10.0` `coloredlogs` dependency relaxed) to be able to do so.

**Comment by paulf81** [comment]
Thanks for raising this issue @pjireland , I've opened a pull request (#939) to look at updating FLORIS' requirements

**Comment by pjireland** [comment]
> Thanks for raising this issue @pjireland , I've opened a pull request (#939) to look at updating FLORIS' requirements

Great - thanks, @paulf81!

**Comment by paulf81** [comment]
Resolved in #939
