### ISSUE TITLE
Out of date documentation - readthedocs

### ISSUE THREAD

**Issue by rafmudaf** [NREL/floris#95]
**Bug description**
On the current `develop` branch (pre v2 release), the readthedocs documentation is outdated and out of sync from the repository.

The following sections should be updated:

- [x] Background and Objectives: include the GCH features and changes to the "gauss" models
- [x] Theory: include the GCH features and changes to the "gauss" models
- [x] Code Reference: this no longer correctly maps to the docstrings for the wake models since the directory structure has changed
- [ ] Inputs: add new API requirements
- [x] Examples: is this still relevant? If so, this should be updated to match the reworked examples
- [x] Testing: update status of regression tests and details of unit tests (`SampleInputs`)
- [x] Change Log: Include v2.0.0 changes

**Floris Version**
`develop` branch as of April 17, 2020.

**Additional context**
Here's the link to the public documentation: https://floris.readthedocs.io. The default branch is `develop`.

**Comment by paulf81** [comment]
Good catch, maybe on Monday we can discuss a group effort to divide and conquer reviewing and updating docstrings and documentation?
