### ISSUE TITLE
ParallelFlorisModel updated to match FlorisModel API

### ISSUE THREAD

**Issue by paulf81** [NREL/floris#971]
# ParallelFlorisModel updated to match FlorisModel API

ParallelFlorisModel currently has an API not exactly 1-1 with FlorisModel.  This may be necessary, for example in order to defer certain calculations until splitting onto cores, however ideally the variance will be minimized as much as possible.  This issue is a placeholder to hold the intention to do some improvements in this vane and more generally.

## Proposed solution

- [x] Provide default values to max_workers and n_wind_condition_splits based on detection of available cores
- [x] Remove unsupported parallel computing interfaces, perhaps standardize on one?
- [x] Make sure all control vectors are supported, not just yaw
- [x] Remove no_wake flags in favor of run, run_no_wake style of v4
- [x] Match as close as possible FlorisModel interface

## Additional context
 A small subset of improvements was added in #967

**Comment by misi9170** [comment]
Closed by #982
