### ISSUE TITLE
.yaml file

### ISSUE THREAD

**Issue by Qutianyuan0124** [NREL/floris#978]
### Discussed in https://github.com/NREL/floris/discussions/547

<div type='discussions-op-text'>

<sup>Originally posted by **prith-gs** December  8, 2022</sup>
Can I add a new (custom) wake deficit model on my own and use it to calculate AEP for a wind farm?</div>

**Comment by Qutianyuan0124** [comment]
No matter how I configure the turbine radius and rotor diameter in the YAML file of the turbine library, it always defaults to 126m during application. How can I customize the turbine?

**Comment by misi9170** [comment]
> No matter how I configure the turbine radius and rotor diameter in the YAML file of the turbine library, it always defaults to 126m during application. How can I customize the turbine?

Hi @Qutianyuan0124 , thanks for the question! See my response over on #979

**Comment by misi9170** [comment]
Closing this issue, as I believe it is resolved in #979

**Comment by Qutianyuan0124** [comment]
hello，

Recently, I have been researching how to optimize wind turbine layouts. When I use the Example layout method for optimization, I find that I cannot find the optimal layout. However, when I use the Generic random search for optimization, I notice that the turbine layout is very irregular and aesthetically unpleasing. Do you have any methods to ensure the turbines are arranged neatly and aligned with the dominant wind direction? I have tried using the SLSQP method, but I am unable to integrate it into the Generic random search code. Do you have any good suggestions for this?

sincerely，
qutianyuan



***@***.***
 
From: misi9170
Date: 2024-09-25 03:42
To: NREL/floris
CC: Qutianyuan0124; Mention
Subject: Re: [NREL/floris] .yaml file (Issue #978)
Closing this issue, as I believe it is resolved in #979
―

**Comment by Qutianyuan0124** [comment]
Assuming that my dominant wind direction is from the west, how can I arrange the turbines neatly while ensuring a certain improvement in energy production? The image below shows my optimized layout, which appears very scattered.


***@***.***
 
发件人： 瞿天元
发送时间： 2024-09-27 16:35
收件人： NREL/floris
主题： Re: Re: [NREL/floris] .yaml file (Issue #978)
hello，

Recently, I have been researching how to optimize wind turbine layouts. When I use the Example layout method for optimization, I find that I cannot find the optimal layout. However, when I use the Generic random search for optimization, I notice that the turbine layout is very irregular and aesthetically unpleasing. Do you have any methods to ensure the turbines are arranged neatly and aligned with the dominant wind direction? I have tried using the SLSQP method, but I am unable to integrate it into the Generic random search code. Do you have any good suggestions for this?

sincerely，
qutianyuan



***@***.***
 
From: misi9170
Date: 2024-09-25 03:42
To: NREL/floris
CC: Qutianyuan0124; Mention
Subject: Re: [NREL/floris] .yaml file (Issue #978)
Closing this issue, as I believe it is resolved in #979
―

**Comment by misi9170** [comment]
Hi @Qutianyuan0124 ,

No, we don't currently have any in-built methods that generate "neat" layouts that also maximize AEP. We recently added a layout optimizer `LayoutOptimizationGridded` that does indeed generate gridded layouts (see #976, or [this example](https://github.com/NREL/floris/pull/976/files#diff-a4ab55a49941ba5dd31a069cbe4cdf55e88fd067161aaa1d5a85b06c9f10d6f4))---however, the intention with that is to pack as many turbines as possible into a given boundary area, which is a proxy for maximizing AEP, rather than taking a fixed number of turbines and arranging them in a neat way to maximize AEP.

We'd be interested in what you find if you decide to build your own layout optimizer that maximizes AEP while keeping turbines in a neat arrangement!

Misha

**Comment by Qutianyuan0124** [comment]
I'm trying this example, when an error prompt is as follows: the from floris. Optimization. Layout_optimization. Layout_optimization_gridded import (

ModuleNotFoundError: No module named 'floris.optimization.layout_optimization.layout_optimization_gridded' Do I need to update floris or modify the configuration file. Also, I would be very grateful if you could tell me the path of the original code file about the optimized layout



***@***.***
 
From: misi9170
Date: 2024-09-28 05:01
To: NREL/floris
CC: Qutianyuan0124; Mention
Subject: Re: [NREL/floris] .yaml file (Issue #978)
Hi @Qutianyuan0124 ,
No, we don't currently have any in-built methods that generate "neat" layouts that also maximize AEP. We recently added a layout optimizer LayoutOptimizationGridded that does indeed generate gridded layouts (see #976, or this example)---however, the intention with that is to pack as many turbines as possible into a given boundary area, which is a proxy for maximizing AEP, rather than taking a fixed number of turbines and arranging them in a neat way to maximize AEP.
We'd be interested in what you find if you decide to build your own layout optimizer that maximizes AEP while keeping turbines in a neat arrangement!
Misha

**Comment by Qutianyuan0124** [comment]
Hi,
I used genetic random search for optimization, but the yield was lower, and I couldn't figure out what was wrong. Attached is my time series data, boundary and code files. Could you please help me check them.



***@***.***
 
From: misi9170
Date: 2024-09-28 05:01
To: NREL/floris
CC: Qutianyuan0124; Mention
Subject: Re: [NREL/floris] .yaml file (Issue #978)
Hi @Qutianyuan0124 ,
No, we don't currently have any in-built methods that generate "neat" layouts that also maximize AEP. We recently added a layout optimizer LayoutOptimizationGridded that does indeed generate gridded layouts (see #976, or this example)---however, the intention with that is to pack as many turbines as possible into a given boundary area, which is a proxy for maximizing AEP, rather than taking a fixed number of turbines and arranging them in a neat way to maximize AEP.
We'd be interested in what you find if you decide to build your own layout optimizer that maximizes AEP while keeping turbines in a neat arrangement!
Misha
